name: Test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.4
      - name: Test Self
        uses: ./../../
        with:
          str: 'Python is bad.'
        id: test_self
      - name: Print Output
        run: 'echo Output of test: ${{ steps.test_self.outputs.str }}'